services:
  db:
    image: postgres:latest
    container_name: blog
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"